title: Colin Drake
baseURL: https://colindrake.me
languageCode: en-us
theme: basic

params:
  menu:
    - url: /post
      name: blog
      description: technical writing
    - url: https://linkedin.com/in/cfdrake
      name: resume
      description: professional work
    - url: /open-source
      name: open source
      description: ios apps, etc. written by me
    - url: /norns
      name: norns
      description: music software written by me
    - url: /music
      name: music
      description: ambient recordings
    - url: /art
      name: art
      description: generative art
    - url: /about
      name: about
      description: bio & contact details
